alg: fedit
suffix: heterogeneous_mcq_4datasets/dataset_skewed
device: 0
dataset: heterogeneous_mcq_4datasets
mcq_train_dir: dataset/heterogeneous_mcq_4datasets/train/dataset_skewed
mcq_dataset_dir: dataset/heterogeneous_mcq_4datasets
mcq_domains:
- medqa
- logiqa
- openbookqa
- sciq
model: llama32_1b_base
model_path: models/models--llama3.2-1B
task_type: CAUSAL_LM
seed: 42
deterministic: true
cn: 16
sr: 1.0
rnd: 10
test_gap: 1
mcq: true
final_only_test: true
skip_mcq_test: false
global_test: false
cross_domain_qa: false
round_generation_metrics: false
bs: 1
grad_accum: 8
epoch: 1
step: 0
lr: 0.0001
eval_batch_size: 8
mode: prototype
lora_rank: 8
lora_alpha: 32
lora_dropout: 0.05
